
%Ui position : [ left, bottom, width, height ]
% paths
addpath("./audio_utils")
addpath("./user_interface")

graphics_toolkit qt

%Global variables
global processed_audio;
global wet_dry_level = 0.5;

%Create the filters place holders
global tl_cmfs = zeros(1,4);      %[29.7,37.1,41.1,43.7];
global tr_cmf = 1;
global tl_apfs = zeros(1,2);      %[96.83,32.92];
global  tr_apfs = zeros(1,2);     %[0.005,0.0017];

function simpleRecordingUI()
    % Create the figure
    hFig = figure('Position', [100, 100, 800, 600], 'Name', 'Schroeder Reverberator', 'NumberTitle', 'off');

    % Create the recorder
    fs = 44100; % Hz 
    nbits = 16; 
    nchannels = 1;
    
    ui_offset = 250
    
    col_1 = 50 ;
    col_2 = 260;
    line_1 = 300 -ui_offset;
    line_2 = 350- ui_offset;
    line_3 = 400- ui_offset;
    line_4 = 450- ui_offset;
    line_5 = 470- ui_offset;
    line_6 = 500- ui_offset;
    line_7 = 530- ui_offset;
    line_8 = 550- ui_offset;
    line_9 = 580- ui_offset;
    line_10 = 600 - ui_offset;
    line_11 = 630 - ui_offset;
    line_12 = 650 - ui_offset;
    line_13 = 680 - ui_offset;
    line_14 = 730 - ui_offset;
    line_15 = 700 - ui_offset;
    
    recorder = audiorecorder(fs, nbits, nchannels);
    hAudioPlayBackBtn = uicontrol('Style', 'pushbutton', 'String', 'Play audio', ...
                            'Position', [col_1, line_1, 200, 40], 'Callback', {@playAudioData, fs}); 

    % Create the Start Recording button
    hStartBtn = uicontrol('Style', 'pushbutton', 'String', 'Start Recording', ...
                          'Position', [col_1, line_3, 200, 40], 'Callback', {@startRecordingCallback, recorder});

    % Create the Stop Recording button
    hStopBtn = uicontrol('Style', 'pushbutton', 'String', 'Stop Recording', ...
                           'Position', [col_1, line_2, 200, 40], 'Callback', {@stopRecordingCallback, recorder, hFig});
    % Wet dry level slider label
    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "Wet/Dry Level", ...
              "position", [col_1, line_5, 200, 20]);

    % Wet dry level slider
    hWetDrySlider = uicontrol("style", "slider", ...
                              "units", "pixel", ...
                              "string", "slider", ...
                              "callback", @updateWetDryLevel, ...
                              "value", 0.4, ...
                              "position", [col_1, line_4, 200, 20]);

    % Comb filter tl text labels and inputs
    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "Comb Filter TL 1", ...
              "position", [col_1, line_7, 200, 20]);
              
    cbf1_tl_text = uicontrol("style", "edit", ...
                             "units", "pixel", ...
                             "string", "29.7", ...
                             "callback", {@updateLoopTimeCombFilter, 1}, ...
                             "position", [col_1, line_6, 200, 30]);
    updateLoopTimeCombFilter(cbf1_tl_text, 1);

    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "Comb Filter TL 2", ...
              "position", [col_1, line_9, 200, 20]);
              
    cbf2_tl_text = uicontrol("style", "edit", ...
                             "units", "pixel", ...
                             "string", "37.1", ...
                             "callback", {@updateLoopTimeCombFilter, 2}, ...
                             "position", [col_1, line_8, 200, 30]);
    updateLoopTimeCombFilter(cbf2_tl_text, 2);

    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "Comb Filter TL 3", ...
              "position", [col_1, line_11, 200, 20]);
    cbf3_tl_text = uicontrol("style", "edit", ...
                             "units", "pixel", ...
                             "string", "41.1", ...
                             "callback", {@updateLoopTimeCombFilter, 3}, ...
                             "position", [col_1, line_10, 200, 30]);
    updateLoopTimeCombFilter(cbf3_tl_text, 3);

    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "Comb Filter TL 4", ...
              "position", [col_1, line_13, 200, 20]);
    cbf4_tl_text = uicontrol("style", "edit", ...
                             "units", "pixel", ...
                             "string", "43.7", ...
                             "callback", {@updateLoopTimeCombFilter, 4}, ...
                             "position", [col_1, line_12, 200, 30]);
    updateLoopTimeCombFilter(cbf4_tl_text, 4);

    % Comb filter tr text label and input
    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "Comb Filter TR", ...
              "position", [col_1, line_14, 200, 20]);
    cbf_tr_text = uicontrol("style", "edit", ...
                            "units", "pixel", ...
                            "string", "1", ...
                            "callback", @updateReverbTimeCombFilter, ...
                            "position", [col_1, line_15, 200, 30]);
    updateReverbTimeCombFilter(cbf_tr_text);

    % All pass filters text labels and inputs
    % apf 1
    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "APF1 TL", ...
              "position", [col_2, line_13, 200, 20]);
    apf1_tl_text = uicontrol("style", "edit", ...
                             "units", "pixel", ...
                             "string", "96.83", ...
                             "callback", {@updateLoopTimeAllPassFilters, 1}, ...
                             "position", [col_2, line_12, 200, 30]);
    updateLoopTimeAllPassFilters(apf1_tl_text, 1);

    % Reverb time
    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "APF1 TR", ...
              "position", [col_2, line_11, 200, 20]);
    apf1_tr_text = uicontrol("style", "edit", ...
                             "units", "pixel", ...
                             "string", "0.005", ...
                             "callback", {@updateReverbTimeAllPassFilters, 1}, ...
                             "position", [col_2, line_10, 200, 30]);
    updateReverbTimeAllPassFilters(apf1_tr_text, 1);

    % apf 2
    % Loop time
    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "APF2 TL", ...
              "position", [col_2, line_9, 200, 20]);
    apf2_tl_text = uicontrol("style", "edit", ...
                             "units", "pixel", ...
                             "string", "32.92", ...
                             "callback", {@updateLoopTimeAllPassFilters, 2}, ...
                             "position", [col_2, line_8, 200, 30]);
    updateLoopTimeAllPassFilters(apf2_tl_text, 2);

    % Reverb time
    uicontrol("style", "text", ...
              "units", "pixel", ...
              "string", "APF2 TR", ...
              "position", [col_2, line_7, 200, 20]);
              
    apf2_tr_text = uicontrol("style", "edit", ...
                             "units", "pixel", ...
                             "string", "0.0017", ...
                             "callback", {@updateReverbTimeAllPassFilters, 2}, ...
                             "position", [col_2, line_6, 200, 30]);
    updateReverbTimeAllPassFilters(apf2_tr_text, 2);

end

simpleRecordingUI();